services:
  - type: web
    name: aniexo
    env: node
    region: oregon
    plan: free
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: node render-start.js
    healthCheckPath: /api/genres
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  
      - key: DATABASE_URL
        fromDatabase:
          name: aniexo-db
          property: connectionString

databases:
  - name: aniexo-db
    plan: free

# Define environment variable groups - uncomment and customize if needed
# envVarGroups:
#   - name: aniexo-secrets
#     envVars:
#       - key: JIKAN_API_KEY
#         value: your-jikan-api-key
#       - key: OPENAI_API_KEY
#         sync: false